server:
  port: 8761
spring:
  security:
    basic:
      enabled: true
    user:
      name: cjr
      password: 123456
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://cjr:123456@127.0.0.1:8761/eureka/
  security:
    basic:
      enabled: true