server:
  port: 7788
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/13636745662/SpringCloudDemo.git
          search-paths:
          - myspringcloudconfig
          username: 13636745662
          password: 
      label: master