spring:
  application:
    name: consumer-ticket
server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true #注册服务时使用服务的ip地址
  client:
    service-url:
      defaultZone: http://cjr:123456@127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true